<a href="https://colab.research.google.com/github/vikasvinay/ML/blob/temp/tf_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount("/content/gdrive")


Mounted at /content/gdrive


In [5]:
#Introduction to tensor

In [6]:
import tensorflow as tf


In [7]:
#creating a tensors
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
#create a vector
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [21]:
#creating a matrix
matrix = tf.constant(([10,7], [5,5]))
matrix
matrix1 = tf.constant(([1,2,3],[4,5,6]), dtype=tf.float16)
matrix1
print(f"matrix1: {matrix1} dimension: {matrix1.ndim}")
print(f"matrix: {matrix} dimension: {matrix.ndim}")

matrix1: [[1. 2. 3.]
 [4. 5. 6.]] dimension: 2
matrix: [[10  7]
 [ 5  5]] dimension: 2


In [23]:
#creating 3 dimension
matrix2 = tf.constant((
    [[
     [1,2,3],[4,5,6],[12,34,56],
     [1,2,3],[4,5,6],[12,34,56]
    ],
     [
     [1,2,3],[4,5,6],[12,34,56],
     [1,2,3],[4,5,6],[12,34,56]
    ],
     [
     [1,2,3],[4,5,6],[12,34,56],
     [1,2,3],[4,5,6],[12,34,56]
    ]
     ]
))
matrix2.ndim

3

In [26]:
# Tensorflow variable
var = tf.Variable("vinay")
var1 = tf.constant(([1,2,3,4]))
var.get_shape, var1

(<bound method Variable.get_shape of <tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'vinay'>>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>)

In [32]:
#random tensorflow
random_1 = tf.random.Generator.from_seed(43)
random_1 = random_1.normal(shape=(2,2))
random_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>